run = docker run
pull = docker pull
build = docker build
stop = docker stop
remove = docker rm

backend-container-name = booking-app-backend
db-container-name = booking-app-db
port = -p 8080:8080
postgres-image = postgres:latest

.PHONY database, stop, clean, clean, backend-image