version: "3"

services:
  database:
    container_name: db
    image: postgres
    environment:
      - POSTGRES_DB=rentify
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - "5432:5432"

  backend:
    container_name: booking-app-backend
    depends_on:
      - database
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/rentify
    build:
      context: booking-app-backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  frontend:
    container_name: booking-app-frontend
    depends_on:
      - backend
    build:
      context: booking-app-frontend
      dockerfile: Dockerfile
    ports:
      - "80:3000"